# Generated by Django 2.0.7 on 2018-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=20)),
                ('race_number', models.SmallIntegerField()),
                ('race_name', models.CharField(max_length=255)),
                ('order_of_finish', models.SmallIntegerField()),
                ('frame_number', models.SmallIntegerField()),
                ('horse_number', models.SmallIntegerField()),
                ('horse_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.SmallIntegerField()),
                ('time_g', models.FloatField()),
                ('horse_weight', models.FloatField()),
                ('margin', models.CharField(max_length=20)),
                ('time_3f', models.FloatField()),
                ('jockey_name', models.CharField(max_length=50)),
                ('load_weight', models.FloatField()),
                ('odds_order', models.SmallIntegerField()),
                ('odds', models.FloatField()),
                ('trainer_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'analysis_race_result',
            },
        ),
    ]
